- name: Learning fact variables
  hosts: all
  tasks:
    - name: Print OS name
      debug:
        var: ansible_distribution

    - name: Print memory details
      debug:
        var: ansible_memory_mb

    - name: Print memory details
      debug:
        var: ansible_memory_mb.real.free

    - name: Print processor name
      debug:
        var: ansible_processor[2]
