apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  type: NodePort
  ports:
    - port: 8090
      nodePort: 30001
      targetPort: vproapp-port
      protocol: TCP
    selector:
      app: vproapp
